apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080 # 외부 port
      targetPort: 8080 # 컨테이너 내부의 pod의 port
