version: "3.8"

services: 
  server:
    image: 'nginx:stable-alpine'
    ports: 
      - '8000:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # ro: 읽기전용
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated # delegated는 호스트머신에서 처리하지 않고 batch로 기본처리함으로 성능 약간 향상(안정성은 떨어짐)
    # 해당 포트는 소용이 없음(nginx에서 설정하여 컨테이너 간 직접 통신을 하기 때문)
    # ports:
    #   - '3000:9000'
  mysql:
    image: mysql:8.0
    # image: mysql:5.7 # Mac M1에서 안됨
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  # artisan:
  # npm:
