apiVersion: v1
kind: Service 
metadata:
  name: backend # service 이름
spec:
  selector: 
    app: second-app # second-app이 있는 service는 모두 제어 가능
    # tier: backend
  ports:
    - protocol: 'TCP' # 기본 TCP
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer
