apiVersion: v1
kind: Deployment 
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  template:
  selector: 
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer
