apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec: # deployment의 사양
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: haservi/kub-demo-users
