apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: haservi/kub-data-demo:2
          env:
            - name: STORY_FOLDER # env 설정값 넣기
              # value: 'story'
              valueFrom: 
                configMapKeyRef: # 특정 config 지정
                  name: data-store-env
                  key: folder # STORY_FOLDER 값 매칭
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
